uint32 cell_num
uint32 run_time
uint32 hsoc
float64 voltage
uint32 cur_cadc
float64[6] temp
uint32 temp1
uint32 temp2
uint32 temp3
uint32 temp4
uint32 temp5
uint32 temp6
float64 tmax
float64 tmin
uint32 vmax
uint32 vmin
uint32 vmaxmin_no
uint32 rsoc
float64 fcc
float64 rc
uint32 cycle_count
uint32 protect
uint32 alarm
uint32 pack_status
uint32[17] vcell
uint32 vcell1
int32 state
uint32 soc
int32 status
int64 error_code
# uint32 vcell2
# uint32 vcell3
# uint32 vcell4
# uint32 vcell5
# uint32 vcell6
# uint32 vcell7
# uint32 vcell8
# uint32 vcell9
# uint32 vcell10
# uint32 vcell11
# uint32 vcell12
# uint32 vcell13
# uint32 vcell14
# uint32 vcell15
# uint32 vcell16
# uint32 vcell17
# uint32 vcell18
# uint32 vcell19
# uint32 vcell20
# uint32 vcell21
# uint32 vcell22
# uint32 vcell23
# uint32 vcell24
# uint32 vcell25
# uint32 vcell26
# uint32 vcell27
# uint32 vcell28
# uint32 vcell29
# uint32 vcell30
# uint32 vcell31
# uint32 vcell32